### ISSUE TITLE
'SH1107_I2C' object has no attribute 'large_text'

### ISSUE THREAD

**Issue by stephanedeR** [peter-l5/framebuf2#5]
Dear, 

Thanks for you time. 
I'm trying to tes your SH1107.py software on a 0.96 display 128x64 dot. 
On my side, adress

**Comment by stephanedeR** [comment]
I'm using I2C protocol and my adress are 0x3C (not 0x3D). I'm in trouble with Large texte features. I 'already place Framebuf2 on my PICO software and I'm using thonny to develop code. 

I don't know why but I have : 
Traceback (most recent call last):
  File "<stdin>", line 138, in <module>
AttributeError: 'SH1107_I2C' object has no attribute 'large_text'
Could you help me with this error ? 

Best regards 
 stephane

**Comment by peter-l5** [comment]
Hi stephane,
I can try and help you. However, to help I will need more information on the problem you have found.
First can I check: On your PICO there should be at least three files: the module code: `sh1107.py` and `framebuf2.py`, plus also the program that you are running. Is that correct?
Secondly, I would need to see the log output from much more of your program, ideally all of it, so that I can see the error in context. Can you paste that in your reply?
best
Peter

**Comment by peter-l5** [comment]
Hi stephane,
I'm still happy to try and help if you can send some more information about the problem you encountered - as per previous message. I am also keen to understand if you might have come across a bug in the module code. Or maybe you have been able to solve the problem. 
Let me know. If I don't hear from you in a week or so I will close the issue.
best
Peter

**Comment by peter-l5** [comment]
Closing this issue. 
Let me know if the problem reoccurs.
